
pub use author::*;
pub use category::*;
pub use icon::*;
pub use id_and_uuid_reference::*;
pub use id_reference::*;
pub use resource::*;
pub use resource_file::*;
pub use resource_rating::*;
pub use resource_review::*;
pub use resource_update::*;
pub use resource_version::*;
pub use inline_response200::*;
pub use inline_response200_1::*;
pub use inline_response200_2::*;
pub use inline_response200_3::*;
pub use inline_response200_stats::*;
pub use inline_response200_status::*;
pub use inline_response200_status_fetch::*;
pub use inline_response200_status_fetch_page::*;
pub use inline_response200_status_fetch_page_item::*;
mod author;
mod category;
mod icon;
mod id_and_uuid_reference;
mod id_reference;
mod resource;
mod resource_file;
mod resource_rating;
mod resource_review;
mod resource_update;
mod resource_version;
mod inline_response200;
mod inline_response200_1;
mod inline_response200_2;
mod inline_response200_3;
mod inline_response200_stats;
mod inline_response200_status;
mod inline_response200_status_fetch;
mod inline_response200_status_fetch_page;
mod inline_response200_status_fetch_page_item;